import "./globals.css";
import { inter } from './fonts'
import { AppSidebar }  from "@/components/AppSidebar"; 
import { SidebarProvider } from "@/components/ui/sidebar";

export const metadata = {
  title: "Tarjetas de estudio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <div className="flex items-center justify-center h-full w-auto">
        <SidebarProvider>
          <AppSidebar />
        </SidebarProvider>
        </div>
        
        
        {children}
      </body>
    </html>
  );
}
