import "./globals.css";
import { inter } from './fonts'

export const metadata = {
  title: "Tarjetas de estudio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
